kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  tls:
    - hosts:
        - cdn.{{ .Values.config.baseDomain }}
      secretName: cdn-tls
  rules:
    - host: cdn.{{ .Values.config.baseDomain }}
      http:
        paths:
          - path: /api/v1/public
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.port }}
